FROM localhost/base:latest

USER root

COPY packages /

# Install common base packages
RUN grep -v '^#' /packages | \
    xargs pacman -Syyu --needed --noconfirm && \
    rm /packages

USER build
WORKDIR /home/build
COPY aur-packages /home/build

# Install & init yay
RUN grep -v '^#' /home/build/aur-packages | \
    xargs yay -S --noconfirm
